'use client';
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {db,configured} from '../lib/client';
type Member={id:string;name:string;phone:string;role:string;member_code:string};
type Lot={id:string;customer_id:string;remaining:number;expires_at:string};
type Reward={id:string;customer_id:string;name:string;expires_at:string;redeemed_at:string|null};
type Tx={id:string;customer_id:string;kind:string;amount:number;points:number;reference:string;created_at:string;payment_method?:string};
const defaults={reward_threshold:30000,reward_name:'Special Curry',reward_mode:'once',balance_years:3,reward_years:1,point_unit:1000};
const money=(v:number)=>new Intl.NumberFormat('en-US').format(v)+' MMK';
const expiry=(years:number)=>{const d=new Date();d.setFullYear(d.getFullYear()+years);return d.toISOString()};
const demoMembers:Member[]=[{id:'c1',name:'Thukha Aung',phone:'09 123 456 789',role:'customer',member_code:'DC-0001'},{id:'c2',name:'May Thu',phone:'09 987 654 321',role:'customer',member_code:'DC-0002'},{id:'c3',name:'Aung Min',phone:'09 456 123 789',role:'customer',member_code:'DC-0003'}];
export default function Page(){
const [me,setMe]=useState<Member|null>(null),[view,setView]=useState('Overview'),[demoRole,setDemoRole]=useState('admin'),[members,setMembers]=useState<Member[]>(configured?[]:demoMembers),[lots,setLots]=useState<Lot[]>(configured?[]:[{id:'l1',customer_id:'c1',remaining:30000,expires_at:expiry(3)}]),[rewards,setRewards]=useState<Reward[]>(configured?[]:[{id:'r1',customer_id:'c1',name:'Special Curry',expires_at:expiry(1),redeemed_at:null}]),[tx,setTx]=useState<Tx[]>([]),[settings,setSettings]=useState(defaults),[selected,setSelected]=useState('c1'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[signup,setSignup]=useState(false),[qr,setQr]=useState(''),[kind,setKind]=useState('topup'),[amount,setAmount]=useState('30000'),[method,setMethod]=useState('Cash'),[reference,setReference]=useState(''),[rewardId,setRewardId]=useState('');
const role=configured?me?.role:demoRole;
const customer=members.find(m=>m.id===(role==='customer'?(configured?me?.id:'c1'):selected));
const balance=(id:string)=>lots.filter(l=>l.customer_id===id&&new Date(l.expires_at)>new Date()).reduce((s,l)=>s+Number(l.remaining),0);
const available=(id:string)=>rewards.filter(r=>r.customer_id===id&&!r.redeemed_at&&new Date(r.expires_at)>new Date());
const points=(id:string)=>tx.filter(t=>t.customer_id===id).reduce((s,t)=>s+Number(t.points),0);
async function refresh(){if(!db)return;const session=await db.auth.getSession();if(!session.data.session){setMe(null);return;}const results=await Promise.all([db.from('profiles').select('*'),db.from('credit_lots').select('*'),db.from('rewards').select('*'),db.from('transactions').select('*').order('created_at',{ascending:false}),db.from('settings').select('*').eq('id',1).single()]);const err=results.find(r=>r.error)?.error;if(err){setNotice(err.message);return;}const list=results[0].data as Member[];setMe(list.find(x=>x.id===session.data.session!.user.id)||null);setMembers(list.filter(x=>x.role==='customer'));setSelected(old=>list.some(x=>x.id===old)?old:list.find(x=>x.role==='customer')?.id||'');setLots(results[1].data as Lot[]);setRewards(results[2].data as Reward[]);setTx(results[3].data as Tx[]);setSettings(results[4].data as typeof defaults);}
useEffect(()=>{refresh();if(db){const {data}=db.auth.onAuthStateChange(()=>{setTimeout(refresh,0)});return()=>data.subscription.unsubscribe()}},[]);
useEffect(()=>{if(role==='customer'&&view!=='My Profile'&&view!=='History')setView('My Profile')},[role,view]);
useEffect(()=>{if(customer)QRCode.toDataURL(customer.member_code,{width:210,margin:2}).then(setQr).catch(()=>setQr(''));else setQr('')},[customer?.member_code]);
async function auth(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(!db)return;const r=signup?await db.auth.signUp({email,password,options:{data:{name}}}):await db.auth.signInWithPassword({email,password});if(r.error)throw r.error;setNotice(signup?'Account created. Check your email to confirm your account.':'Signed in.');await refresh()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
async function submit(e:React.FormEvent){e.preventDefault();if(busy||!customer)return;setBusy(true);try{const n=kind==='reward'?0:Number(amount);if(!Number.isSafeInteger(n)||n<0||(kind!=='reward'&&n===0)||n>100000000)throw Error('Enter a valid whole MMK amount.');if(reference.trim().length<2)throw Error('Enter a receipt or invoice reference.');if(kind==='reward'&&!rewardId)throw Error('Choose a reward.');if(!db&&tx.some(t=>t.customer_id===customer.id&&t.kind===kind&&t.reference===reference.trim()))throw Error('This reference was already recorded.');if(kind==='spend'&&n>balance(customer.id))throw Error('Insufficient balance.');if(db){const r=await db.rpc('post_transaction',{p_request:crypto.randomUUID(),p_customer:customer.id,p_kind:kind,p_amount:n,p_method:kind==='topup'?method:null,p_reference:reference,p_reward:rewardId||null});if(r.error)throw r.error;await refresh();const session=await db.auth.getSession();if(session.data.session&&process.env.NEXT_PUBLIC_GOOGLE_WALLET_ENABLED==='true'){const sync=await fetch('/api/wallet/sync',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.data.session.access_token},body:JSON.stringify({customerId:customer.id})});if(!sync.ok){setNotice('Transaction saved. Google card update failed; customer can retry Add to Google Wallet.');setReference('');setRewardId('');return;}}}else{const id=crypto.randomUUID();if(kind==='topup'){setLots(v=>[...v,{id,customer_id:customer.id,remaining:n,expires_at:expiry(settings.balance_years)}]);const count=n<settings.reward_threshold?0:settings.reward_mode==='once'?1:Math.floor(n/settings.reward_threshold);if(count>1000)throw Error('Too many rewards.');setRewards(v=>[...v,...Array.from({length:count},()=>({id:crypto.randomUUID(),customer_id:customer.id,name:settings.reward_name,expires_at:expiry(settings.reward_years),redeemed_at:null}))])}if(kind==='spend'){let due=n;setLots(lots.map(l=>({...l})).sort((a,b)=>a.expires_at.localeCompare(b.expires_at)).map(l=>{if(l.customer_id===customer.id&&new Date(l.expires_at)>new Date()){const take=Math.min(l.remaining,due);due-=take;return {...l,remaining:l.remaining-take}}return l}))}if(rewardId)setRewards(v=>v.map(r=>r.id===rewardId?{...r,redeemed_at:new Date().toISOString()}:r));setTx(v=>[{id,customer_id:customer.id,kind,amount:n,points:kind==='spend'?Math.floor(n/settings.point_unit):0,reference,created_at:new Date().toISOString()},...v])}setReference('');setRewardId('');setNotice('Transaction recorded successfully. The signed-in profile shows the current balance.')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
async function wallet(provider:string){if(!db){setNotice('Connect Supabase and wallet credentials to issue real cards.');return;}setBusy(true);try{const {data}=await db.auth.getSession();const r=await fetch('/api/wallet/'+provider,{method:'POST',headers:{Authorization:'Bearer '+data.session?.access_token}});if(!r.ok){const d=await r.json();throw Error(d.error)}if(provider==='google'){const d=await r.json();window.location.assign(d.url)}else{const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='bonsine.pkpass';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
async function saveSettings(e:React.FormEvent){e.preventDefault();setBusy(true);try{if(db){const r=await db.from('settings').update(settings).eq('id',1);if(r.error)throw r.error;}setNotice('Settings saved. Existing credit and reward expiry dates stay unchanged.')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
const card=<><div className="membercard"><div className="cardhead"><span>DINING CLUB</span><span>MEMBER</span></div><h2>{customer?.name||'Select a customer'}</h2><p>{customer?.member_code}</p><small>AVAILABLE BALANCE</small><h1>{money(customer?balance(customer.id):0)}</h1><div className="cardbottom"><span>{customer?points(customer.id):0} points</span><span>{customer?available(customer.id).length:0} rewards</span></div></div>{qr&&<div className="qr"><img src={qr} alt="Member identification QR code"/><div><strong>Your member QR</strong><p>Show this card at the counter. Staff will confirm your purchase.</p></div></div>}</>;
if(configured&&!me)return <main className="login"><section><div className="brand">◈ Dining Club</div><h1>Your table. Your rewards.</h1><p>Sign in to view your dining balance and member card.</p><form onSubmit={auth}>{signup&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{signup?'Create account':'Sign in'}</button></form><button className="ghost" onClick={()=>setSignup(!signup)}>{signup?'Already a member? Sign in':'Create a member account'}</button><p role="status">{notice}</p></section></main>;
return <div className="shell"><aside><div className="brand">◈ Dining Club</div><small>MEMBER MANAGEMENT</small><nav>{(role==='customer'?['My Profile','History']:['Overview','Customers','Transactions',...(role==='admin'?['Settings']:[])]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v}</button>)}</nav><div className="asidebottom"><strong>{configured?me?.name:'Demo workspace'}</strong><p>{role==='customer'?'Member':role==='admin'?'Administrator':'Staff'}</p>{db?<button className="ghost" onClick={()=>db?.auth.signOut()}>Sign out</button>:<label>Preview as<select value={demoRole} onChange={e=>{setDemoRole(e.target.value);setView(e.target.value==='customer'?'My Profile':'Overview')}}><option value="admin">Admin</option><option value="staff">Staff</option><option value="customer">Customer</option></select></label>}</div></aside><main><header><div><small>DINING CLUB / {role==='customer'?'MEMBER PORTAL':'CRM'}</small><h1>{role==='customer'&&view!=='History'?'My Profile':view}</h1></div><span className="pill">{configured?'Connected workspace':'DEMO · no real money'}</span></header>{!configured&&<div className="banner">Interactive demo. Changes reset on reload. Real sign-in and secure records activate after Supabase setup.</div>}{notice&&<div className="notice" role="status">{notice}<button className="ghost" onClick={()=>setNotice('')}>Dismiss</button></div>}
{role==='customer'&&view!=='History'?<div className="columns"><section>{card}<p>Apple or Google Wallet is optional. Your card and balance are always available here after sign-in.</p><div className="packages"><button disabled={busy} onClick={()=>wallet("google")}>Add to Google Wallet</button><button disabled={busy} onClick={()=>wallet("apple")}>Add to Apple Wallet</button></div><p className="muted">Google cards refresh when staff record a transaction. Download Apple card again to refresh. Your profile always shows the current balance.</p></section><section className="panel"><h2>My rewards</h2>{customer&&available(customer.id).map(r=><div className="reward" key={r.id}><strong>{r.name}</strong><p>Available · Expires {new Date(r.expires_at).toLocaleDateString()}</p></div>)}{customer&&!available(customer.id).length&&<p>No available rewards yet.</p>}<h2>Balance expiry</h2>{lots.filter(l=>l.customer_id===customer?.id&&l.remaining>0).map(l=><p key={l.id}>{money(l.remaining)} · {new Date(l.expires_at).toLocaleDateString()}</p>)}</section></div>:null}
{role!=='customer'&&view==='Overview'&&<><div className="stats"><article><small>CUSTOMERS</small><h1>{members.length}</h1></article><article><small>UNEXPIRED CREDIT</small><h1>{money(members.reduce((s,m)=>s+balance(m.id),0))}</h1></article><article><small>AVAILABLE REWARDS</small><h1>{members.reduce((s,m)=>s+available(m.id).length,0)}</h1></article></div><section className="panel"><div className="sectionhead"><h2>Members</h2><button onClick={()=>setView('Transactions')}>Record transaction</button></div>{members.map(m=><button className="memberrow" key={m.id} onClick={()=>{setSelected(m.id);setView('Customers')}}><span><strong>{m.name}</strong><small>{m.phone||'No phone recorded'}</small></span><strong>{money(balance(m.id))}</strong><span>{available(m.id).length} rewards</span></button>)}{!members.length&&<p>No customers yet. Customers can create their accounts through the sign-in page.</p>}</section></>}
{role!=='customer'&&view==='Customers'&&<div className="columns"><section className="panel"><h2>Customer directory</h2><input placeholder="Search name, phone or scanned member code" value={query} onChange={e=>setQuery(e.target.value)}/>{members.filter(m=>(m.name+' '+m.phone+' '+m.member_code).toLowerCase().includes(query.toLowerCase())).map(m=><button className={'memberrow '+(selected===m.id?'chosen':'')} key={m.id} onClick={()=>setSelected(m.id)}><span><strong>{m.name}</strong><small>{m.phone}</small></span><span>{money(balance(m.id))}</span></button>)}</section><section>{card}<button onClick={()=>setView('Transactions')}>Record transaction</button></section></div>}
{role!=='customer'&&view==='Transactions'&&<div className="columns"><section className="panel"><h2>Record transaction</h2><form onSubmit={submit}><label>Customer<select value={selected} onChange={e=>{setSelected(e.target.value);setRewardId('')}} required><option value="">Select customer</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><div className="tabs">{['topup','spend','reward'].map(k=><button type="button" className={kind===k?'active':''} key={k} onClick={()=>{setKind(k);setRewardId('')}}>{k==='topup'?'Top up':k==='spend'?'Pay bill':'Use reward'}</button>)}</div>{kind!=='reward'&&<><label>{kind==='spend'?'Paid amount after free reward (MMK)':'Top-up amount (MMK)'}<input type="number" min="1" max="100000000" step="1" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>{kind==='topup'&&<div className="packages">{[30000,50000,100000].map(n=><button type="button" className="ghost" key={n} onClick={()=>setAmount(String(n))}>{n.toLocaleString()}</button>)}<span>or enter custom amount</span></div>}</>}{kind==='topup'&&<label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}>{['Cash','KBZPay','Wave'].map(m=><option key={m}>{m}</option>)}</select></label>}{kind!=='topup'&&<label>Reward {kind==='spend'?'(optional)':''}<select value={rewardId} onChange={e=>setRewardId(e.target.value)} required={kind==='reward'}><option value="">{kind==='spend'?'No reward':'Select reward'}</option>{customer&&available(customer.id).map(r=><option value={r.id} key={r.id}>{r.name} · {new Date(r.expires_at).toLocaleDateString()}</option>)}</select></label>}<label>Receipt / invoice reference<input required minLength={2} value={reference} onChange={e=>setReference(e.target.value)} placeholder="INV-0001 / payment reference"/></label><p className="muted">Confirm payment or bill details before recording. Reward-only redemption earns no points.</p><button disabled={busy||!customer}>{busy?'Recording…':'Confirm transaction'}</button></form></section><section>{card}<section className="panel"><h2>Recent activity</h2>{tx.filter(t=>t.customer_id===selected).slice(0,6).map(t=><div className="activity" key={t.id}><strong>{t.kind} · {money(t.amount)}</strong><p>{t.reference} · +{t.points} points</p></div>)}</section></section></div>}
{view==='History'&&<section className="panel"><h2>My activity</h2>{tx.filter(t=>t.customer_id===customer?.id).map(t=><div className="activity" key={t.id}><strong>{t.kind} · {money(t.amount)}</strong><p>{t.reference} · {new Date(t.created_at).toLocaleString()} · +{t.points} points</p></div>)}{!tx.some(t=>t.customer_id===customer?.id)&&<p>No activity yet.</p>}</section>}
{role==='admin'&&view==='Settings'&&<section className="panel settings"><h2>Membership rules</h2><form onSubmit={saveSettings}><label>Reward threshold (MMK)<input type="number" min="1" required value={settings.reward_threshold} onChange={e=>setSettings({...settings,reward_threshold:Number(e.target.value)})}/></label><label>Reward name<input required value={settings.reward_name} onChange={e=>setSettings({...settings,reward_name:e.target.value})}/></label><label>Reward allocation<select value={settings.reward_mode} onChange={e=>setSettings({...settings,reward_mode:e.target.value})}><option value="once">One reward per qualifying top-up</option><option value="multiple">One reward per threshold multiple</option></select></label><label>Balance validity (years)<input type="number" min="1" max="10" required value={settings.balance_years} onChange={e=>setSettings({...settings,balance_years:Number(e.target.value)})}/></label><label>Reward validity (years)<input type="number" min="1" max="10" required value={settings.reward_years} onChange={e=>setSettings({...settings,reward_years:Number(e.target.value)})}/></label><label>MMK spent for 1 point<input type="number" min="1" required value={settings.point_unit} onChange={e=>setSettings({...settings,point_unit:Number(e.target.value)})}/></label><p>Changes apply to new transactions. Existing expiry dates stay unchanged.</p><button disabled={busy}>Save rules</button></form></section>}
</main></div>}
