import {createClient} from '@supabase/supabase-js';
import {createSign} from 'node:crypto';
import {PKPass} from 'passkit-generator';
import {readFile} from 'node:fs/promises';
export function adminDb(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error('Server database credentials not configured');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function authorize(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token)throw Error('Sign in required');const db=adminDb();const {data,error}=await db.auth.getUser(token);if(error||!data.user)throw Error('Invalid session');return {db,user:data.user}}
export async function snapshot(id:string){const db=adminDb();const rows=await Promise.all([db.from('profiles').select('*').eq('id',id).single(),db.from('credit_lots').select('*').eq('customer_id',id),db.from('transactions').select('points').eq('customer_id',id),db.from('rewards').select('*').eq('customer_id',id)]);for(const r of rows)if(r.error)throw Error(r.error.message);const now=Date.now();return {profile:rows[0].data,balance:(rows[1].data||[]).filter(x=>Date.parse(x.expires_at)>now).reduce((s,x)=>s+Number(x.remaining),0),points:(rows[2].data||[]).reduce((s,x)=>s+Number(x.points),0),rewards:(rows[3].data||[]).filter(x=>!x.redeemed_at&&Date.parse(x.expires_at)>now).length}}
const b64=(v:unknown)=>Buffer.from(JSON.stringify(v)).toString('base64url');
function jwt(payload:object){const key=process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(!key)throw Error('Google private key not configured');const body=b64({alg:'RS256',typ:'JWT'})+'.'+b64(payload);return body+'.'+createSign('RSA-SHA256').update(body).sign(key,'base64url')}
async function googleToken(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;if(!email)throw Error('Google service account not configured');const now=Math.floor(Date.now()/1000);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt({iss:email,scope:'https://www.googleapis.com/auth/wallet_object.issuer',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})})});const d=await r.json();if(!r.ok)throw Error('Google service account authentication failed');return d.access_token as string}
export async function googlePass(id:string){const s=await snapshot(id);const classId=process.env.GOOGLE_WALLET_CLASS_ID;if(!classId)throw Error('Google loyalty class ID not configured');const objectId=classId.split('.')[0]+'.member_'+id.replace(/-/g,'');const obj={id:objectId,classId,state:'ACTIVE',accountId:s.profile.member_code,accountName:s.profile.name,barcode:{type:'QR_CODE',value:s.profile.member_code},loyaltyPoints:{label:'Balance (MMK)',balance:{string:s.balance.toLocaleString('en-US')+' MMK'}},secondaryLoyaltyPoints:{label:'Points',balance:{int:s.points}},textModulesData:[{id:'rewards',header:'Available rewards',body:String(s.rewards)},{id:'terms',header:'Dining credit',body:'Use at Bon Sine only. No cash withdrawal or transfers. Sign in for expiry dates.'}],linksModuleData:{uris:[{uri:site(),description:'Member profile',id:'profile'}]}};const token=await googleToken();const base='https://walletobjects.googleapis.com/walletobjects/v1/loyaltyObject';const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};const check=await fetch(base+'/'+objectId,{headers,cache:'no-store'});if(!check.ok&&check.status!==404)throw Error('Unable to read Google loyalty card');const r=await fetch(check.status===404?base:base+'/'+objectId,{method:check.status===404?'POST':'PATCH',headers,body:JSON.stringify(obj)});if(!r.ok)throw Error('Google card update failed; check issuer access and class approval');const now=Math.floor(Date.now()/1000);return 'https://pay.google.com/gp/v/save/'+jwt({iss:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,aud:'google',typ:'savetowallet',iat:now,origins:[new URL(site()).origin],payload:{loyaltyObjects:[{id:objectId,classId}]}})}
export function site(){const url=process.env.SITE_URL;if(!url||!url.startsWith('https://'))throw Error('Configure public HTTPS SITE_URL');return url.replace(/\/$/,'')}
export async function applePass(id:string){const s=await snapshot(id);const env=(key:string)=>{const value=process.env[key];if(!value)throw Error(key+' not configured');return value};const decode=(key:string)=>Buffer.from(env(key),'base64');const icon=await readFile(process.cwd()+'/public/wallet-icon.png');const pass=new PKPass({'icon.png':icon,'icon@2x.png':icon,'logo.png':icon},{wwdr:decode('APPLE_WWDR_BASE64'),signerCert:decode('APPLE_SIGNER_CERT_BASE64'),signerKey:decode('APPLE_SIGNER_KEY_BASE64'),signerKeyPassphrase:process.env.APPLE_KEY_PASSPHRASE},{formatVersion:1,serialNumber:id,passTypeIdentifier:env('APPLE_PASS_TYPE_ID'),teamIdentifier:env('APPLE_TEAM_ID'),organizationName:'Bon Sine',description:'Bon Sine dining membership',logoText:'BON SINE',backgroundColor:'rgb(15,29,47)',foregroundColor:'rgb(255,255,255)',labelColor:'rgb(224,183,103)',sharingProhibited:true});pass.type='storeCard';pass.primaryFields.push({key:'balance',label:'BALANCE · MMK',value:s.balance.toLocaleString('en-US')});pass.secondaryFields.push({key:'member',label:'MEMBER',value:s.profile.name});pass.auxiliaryFields.push({key:'points',label:'POINTS',value:s.points},{key:'rewards',label:'REWARDS',value:s.rewards});pass.backFields.push({key:'profile',label:'Profile & current balance',value:site()},{key:'terms',label:'Terms',value:'Dining credit at Bon Sine only. No transfers or cash withdrawals. Check the profile for balance and reward expiry. Download this card again after transactions to refresh the displayed balance.'});pass.setBarcodes({format:'PKBarcodeFormatQR',message:s.profile.member_code,messageEncoding:'iso-8859-1'});return pass.getAsBuffer()}
