import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
await db.exec(readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
const admin='00000000-0000-0000-0000-000000000001',customer='00000000-0000-0000-0000-000000000002',other='00000000-0000-0000-0000-000000000003';
for(const id of [admin,customer,other])await db.query(`insert into auth.users values($1,'test@example.com','{"name":"Test"}')`,[id]);
await db.query(`update profiles set role='admin' where id=$1`,[admin]);
await db.query(`select set_config('test.uid',$1,false)`,[admin]);await db.exec('set role authenticated');
const post=async(kind,amount,reward=null,request=crypto.randomUUID())=>(await db.query('select post_transaction($1,$2,$3,$4,$5,$6,$7) id',[request,customer,kind,amount,'Cash','INV-test',reward])).rows[0].id;
const req=crypto.randomUUID();await post('topup',30000,null,req);await post('topup',30000,null,req);
assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,1);
const reward=(await db.query('select id from rewards')).rows[0].id;
await post('spend',9000,reward);
assert.equal(Number((await db.query('select sum(remaining) n from credit_lots')).rows[0].n),21000);
assert.equal(Number((await db.query('select sum(points) n from transactions')).rows[0].n),9);
await assert.rejects(()=>post('reward',0,reward),/Reward unavailable/);
await assert.rejects(()=>post('spend',99999),/Insufficient/);
assert.equal((await db.query('select count(*)::int n from transactions')).rows[0].n,2);
await db.query(`select set_config('test.uid',$1,false)`,[other]);
assert.equal((await db.query('select * from credit_lots')).rows.length,0);
assert.equal((await db.query('select * from profiles')).rows.length,1);
await assert.rejects(()=>post('topup',30000),/Staff access/);
await assert.rejects(()=>db.query('update profiles set role=\'admin\' where id=$1',[other]),/permission denied/);
await assert.rejects(()=>db.query('update credit_lots set remaining=999999'),/permission denied/);
console.log('PASS: schema, top-up, idempotency, combined redemption, spend points, insufficient balance, repeat redemption, RLS isolation, privilege escalation blocked.');
await db.close();
